'use client';
import { useState, useEffect, memo } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { marked } from 'marked'; 

// --- LAG FIX: Memoized Markdown prevents the page from slowing down while you type ---
const MemoizedMarkdown = memo(({ content }) => (
  <ReactMarkdown 
    remarkPlugins={[remarkGfm]} 
    components={{ a: ({node, ...props}) => <a {...props} className="text-blue-600 font-bold hover:underline" target="_blank" rel="noopener noreferrer" /> }}
  >
    {content}
  </ReactMarkdown>
));

export default function FitnessPage() {
  const [formData, setFormData] = useState({ 
    frequency: '3-4', 
    goal: '',
    experience: 'Beginner',
    experience_custom: '',
    equipment: 'Full Gym',
    equipment_custom: '',
    injuries: '',
    split: 'Upper/Lower',
    split_custom: '',
    notes: ''
  });

  const [response, setResponse] = useState("");
  const [loading, setLoading] = useState(false);
  const [history, setHistory] = useState([]);

  const [showFollowUp, setShowFollowUp] = useState(false);
  const [followUpQuery, setFollowUpQuery] = useState("");
  const [followUpLoading, setFollowUpLoading] = useState(false);

  useEffect(() => {
    const saved = localStorage.getItem('fitness_history');
    if (saved) setHistory(JSON.parse(saved));
  }, []);

  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  // 2. EXPORT FUNCTION (Clean Clone Method)
  const downloadPlan = async (format, content, elementId, filenamePrefix) => {
    const filename = `${filenamePrefix}_${new Date().toISOString().split('T')[0]}`;
    
    // Convert Markdown to clean HTML
    const htmlContent = await marked.parse(content);

    if (format === 'pdf') {
      const html2pdf = (await import('html2pdf.js')).default;
      const pdfWrapper = document.createElement('div');
      
      pdfWrapper.innerHTML = `
        <div style="font-family: Arial, sans-serif; line-height: 1.4; color: #333333; padding: 20px;">
          <style>
            /* Ensures smooth page transitions without cutting text in half */
            h2, h3 { page-break-after: avoid; break-after: avoid; margin-top: 15pt; }
            
            /* Crucial: Prevents bullet points or paragraphs from splitting across pages */
            p, li { 
              page-break-inside: avoid; 
              break-inside: avoid; 
              margin-bottom: 8pt; 
              display: block; /* Helps break-inside logic */
            }
            
            ul, ol { margin-bottom: 12pt; }
            
            .pdf-header { 
              text-align: center; 
              margin-bottom: 25pt; 
              border-bottom: 2px solid #1e3a8a; 
              padding-bottom: 10pt; 
            }
            
            h1 { color: #1e3a8a; font-size: 22pt; margin: 0; text-transform: uppercase; }
            .pdf-subtitle { color: #64748b; font-size: 10pt; margin-top: 5pt; }
            h2 { color: #1e40af; font-size: 16pt; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
          </style>
          <div class="pdf-header">
            <h1>Fitness Training Plan</h1>
            <div class="pdf-subtitle">Generated by AI Fitness Coach • ${new Date().toLocaleDateString()}</div>
          </div>
          <div class="pdf-body">
            ${htmlContent}
          </div>
        </div>
      `;

      const opt = {
        margin: [15, 15, 15, 15], // Standardized 15mm margins
        filename: `${filename}.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { 
          scale: 2, 
          useCORS: true, 
          letterRendering: true,
          scrollY: 0,
          scrollX: 0
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        // Use avoid-all to prioritize keeping blocks together
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] } 
      };

      html2pdf().set(opt).from(pdfWrapper).save();
    }
    
    else if (format === 'word') {
      // --- UPDATED WORD EXPORT WITH TITLE ---
      const wordHeader = `
        <div style="text-align: center; margin-bottom: 20pt; border-bottom: 2px solid #1e3a8a; padding-bottom: 10pt;">
          <h1 style="color: #1e3a8a; font-family: Arial; font-size: 24pt; text-transform: uppercase; margin-bottom: 0;">Fitness Training Plan</h1>
          <p style="color: #64748b; font-family: Arial; font-size: 10pt; margin-top: 5pt;">Generated by AI Fitness Coach • ${new Date().toLocaleDateString()}</p>
        </div>
      `;

      const docContent = `
        <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
          <head><meta charset='utf-8'></head>
          <body style="font-family: Arial; line-height: 1.5;">
            ${wordHeader}
            ${htmlContent}
          </body>
        </html>
      `;

      const blob = new Blob(['\ufeff', docContent], { type: 'application/msword' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${filename}.doc`;
      link.click();
    } 
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setResponse("");
    setShowFollowUp(false);

    const finalData = {
      ...formData,
      experience: formData.experience === 'other' ? formData.experience_custom : formData.experience,
      equipment: formData.equipment === 'other' ? formData.equipment_custom : formData.equipment,
      split: formData.split === 'other' ? formData.split_custom : formData.split,
      type: 'fitness'
    };

    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(finalData),
      });
      const data = await res.json();
      
      if (data.output) {
        setResponse(data.output);
        const now = new Date();
        const newEntry = {
          id: Date.now(),
          date: now.toLocaleDateString(),
          time: now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          inputs: finalData,
          plan: data.output
        };
        const updatedHistory = [newEntry, ...history];
        setHistory(updatedHistory);
        localStorage.setItem('fitness_history', JSON.stringify(updatedHistory));
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleFollowUp = async () => {
    if (!followUpQuery.trim()) return;
    setFollowUpLoading(true);

    try {
      const res = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'fitness',
          isFollowUp: true,
          context: response,
          prompt: followUpQuery
        }),
      });
      const data = await res.json();
      if (data.output) {
        setResponse(prev => prev + "\n\n---\n\n### AI Follow-up Response\n" + data.output);
        setFollowUpQuery("");
      }
    } catch (err) {
      console.error(err);
    } finally {
      setFollowUpLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 p-6 md:p-12">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-10">
          <h1 className="text-4xl font-extrabold text-slate-900 mb-2">🏋️ AI Fitness Coach</h1>
          <p className="text-slate-600">Complete the profile below for a precision plan.</p>
        </div>

        {/* --- MAIN FORM --- */}
        <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200">
          <form onSubmit={handleSubmit} className="space-y-6">
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block font-bold text-slate-700 mb-2">Main Goal</label>
                <input type="text" name="goal" required placeholder="e.g. Build muscle, lose 10lbs..." onChange={handleChange} className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" />
              </div>
              <div>
                <label className="block font-bold text-slate-700 mb-2">Workout days per week</label>
                <input type="text" name="frequency" required placeholder="Enter number (e.g. 3-5)" onChange={handleChange} className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" />
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block font-bold text-slate-700 mb-2">Experience Level</label>
                <select name="experience" onChange={handleChange} className="w-full p-3 border border-slate-300 rounded-lg mb-2">
                  <option value="Beginner">Beginner</option>
                  <option value="Intermediate">Intermediate</option>
                  <option value="Advanced">Advanced</option>
                  <option value="other">Other...</option>
                </select>
                {formData.experience === 'other' && (
                  <input type="text" name="experience_custom" placeholder="Describe your experience..." onChange={handleChange} className="w-full p-3 border-l-4 border-blue-500 bg-blue-50 rounded-r-lg outline-none" />
                )}
              </div>
              <div>
                <label className="block font-bold text-slate-700 mb-2">Access to Equipment</label>
                <select name="equipment" onChange={handleChange} className="w-full p-3 border border-slate-300 rounded-lg mb-2">
                  <option value="Full Gym">Full Gym</option>
                  <option value="Limited Home Gym">Limited Home Gym</option>
                  <option value="Bodyweight Only">Bodyweight Only</option>
                  <option value="other">Other...</option>
                </select>
                {formData.equipment === 'other' && (
                  <input type="text" name="equipment_custom" placeholder="Describe your equipment..." onChange={handleChange} className="w-full p-3 border-l-4 border-blue-500 bg-blue-50 rounded-r-lg outline-none" />
                )}
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <label className="block font-bold text-slate-700 mb-2">Preferred Split</label>
                <select name="split" onChange={handleChange} className="w-full p-3 border border-slate-300 rounded-lg mb-2">
                  <option value="Upper/Lower">Upper / Lower</option>
                  <option value="Push/Pull/Legs">Push / Pull / Legs</option>
                  <option value="Full Body">Full Body</option>
                  <option value="other">Other...</option>
                </select>
                {formData.split === 'other' && (
                  <input type="text" name="split_custom" placeholder="Describe your preferred split..." onChange={handleChange} className="w-full p-3 border-l-4 border-blue-500 bg-blue-50 rounded-r-lg outline-none" />
                )}
              </div>
              <div>
                <label className="block font-bold text-slate-700 mb-2">Injuries / Limitations</label>
                <textarea name="injuries" placeholder="e.g. Bad left knee..." onChange={handleChange} rows="2" className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" />
              </div>
            </div>

            <div>
              <label className="block font-bold text-slate-700 mb-2">Optional Notes</label>
              <textarea name="notes" placeholder="Anything else?" onChange={handleChange} rows="3" className="w-full p-3 border border-slate-300 rounded-lg focus:ring-2 focus:ring-blue-500 outline-none" />
            </div>

            <button type="submit" disabled={loading} className={`w-full py-4 rounded-xl font-bold text-lg text-white flex justify-center items-center gap-3 transition-all ${loading ? "bg-slate-400 cursor-not-allowed" : "bg-blue-600 hover:bg-blue-700 shadow-lg"}`}>
              {loading && (
                <svg className="animate-spin h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
              )}
              {loading ? "Designing Plan..." : "Create Workout Plan"}
            </button>
          </form>
        </div>

        {/* --- RESULTS SECTION --- */}
        {response && (
          <div className="mt-8 bg-white p-8 rounded-2xl shadow-lg border-2 border-blue-100">
            <div className="flex justify-between items-start mb-4">
              <h2 className="text-2xl font-bold text-slate-900">🎯 Your Custom Plan</h2>
              <div className="flex gap-2">
                <button onClick={() => downloadPlan('pdf', response, 'active-plan-content', 'My_Fitness_Plan')} className="text-xs bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded shadow">PDF</button>
                <button onClick={() => downloadPlan('word', response, null, 'My_Fitness_Plan')} className="text-xs bg-blue-600 hover:bg-blue-700 text-white px-3 py-1 rounded shadow">Word</button>
              </div>
            </div>
            
            <div id="active-plan-content" className="prose prose-slate max-w-none mb-8">
              <MemoizedMarkdown content={response} />
            </div>

            {/* Follow-up UI... */}
            <div className="pt-6 border-t border-slate-100">
              {!showFollowUp ? (
                <button onClick={() => setShowFollowUp(true)} className="flex items-center gap-2 text-blue-600 font-bold hover:text-blue-800 transition-colors">💬 Continue with AI</button>
              ) : (
                <div className="space-y-4 animate-in fade-in slide-in-from-top-2">
                  <label className="block font-bold text-slate-700 text-sm">Follow-up Question</label>
                  <textarea 
                    value={followUpQuery}
                    onChange={(e) => setFollowUpQuery(e.target.value)}
                    placeholder="Ask about swaps, form tips, or cardio advice..." 
                    className="w-full p-3 border border-blue-200 bg-blue-50 rounded-lg outline-none focus:ring-2 focus:ring-blue-500 text-sm"
                    rows="2"
                  />
                  <div className="flex flex-col sm:flex-row gap-3">
                    <button 
                      onClick={handleFollowUp} 
                      disabled={followUpLoading || !followUpQuery.trim()} 
                      className={`flex-1 py-2 px-4 rounded-lg font-bold text-white text-sm flex justify-center items-center gap-2 transition-all ${followUpLoading ? "bg-slate-400 cursor-not-allowed" : "bg-blue-600 hover:bg-blue-700 shadow-md active:scale-[0.98]"}`}
                    >
                      {followUpLoading && (
                        <svg className="animate-spin h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                      )}
                      {followUpLoading ? "Asking..." : "Ask Follow-up"}
                    </button>
                    <button 
                      onClick={() => setShowFollowUp(false)} 
                      className="px-4 py-2 text-slate-500 text-sm font-semibold hover:bg-slate-50 rounded-lg transition-colors"
                    >
                      Cancel
                    </button>
                  </div>
                </div>
              )}
            </div>
          </div>
        )}

        {/* --- HISTORY SECTION --- */}
        {history.length > 0 && (
          <div className="mt-16">
            <div className="flex justify-between items-end mb-6">
              <h3 className="text-2xl font-bold text-slate-800">History</h3>
              <button onClick={() => {localStorage.removeItem('fitness_history'); setHistory([]);}} className="text-sm text-red-500 hover:text-red-700 font-semibold underline">Clear History</button>
            </div>
            <div className="space-y-4">
              {history.map((item) => (
                <details key={item.id} className="group bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-all">
                  <summary className="flex justify-between items-center p-5 cursor-pointer bg-slate-50 font-medium text-slate-700 group-hover:bg-slate-100">
                    <div className="flex flex-col">
                      <span className="text-xs text-slate-500 uppercase font-bold tracking-wider">{item.date} • {item.time}</span>
                      <span className="font-bold text-slate-900 text-lg mt-1">{item.inputs ? item.inputs.goal : item.goal}</span>
                    </div>
                    <span className="text-slate-400 group-open:rotate-180 transition-transform">▼</span>
                  </summary>
                  <div className="p-6 border-t border-slate-100 bg-gray-50">
                    
                    {/* PLAN PARAMETERS (User Input Receipts) */}
                    {item.inputs && (
                      <div className="mb-6 bg-blue-50 border border-blue-100 p-4 rounded-lg text-sm text-slate-700">
                        <h4 className="font-bold text-blue-900 mb-2 border-b border-blue-200 pb-1">Plan Parameters</h4>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-x-4 gap-y-2">
                          <p><span className="font-semibold">Frequency:</span> {item.inputs.frequency} days/week</p>
                          <p><span className="font-semibold">Experience:</span> {item.inputs.experience}</p>
                          <p><span className="font-semibold">Equipment:</span> {item.inputs.equipment}</p>
                          <p><span className="font-semibold">Split:</span> {item.inputs.split}</p>
                          {item.inputs.injuries && <p className="md:col-span-2"><span className="font-semibold text-red-600">Injuries:</span> {item.inputs.injuries}</p>}
                          {item.inputs.notes && <p className="md:col-span-2"><span className="font-semibold">Notes:</span> {item.inputs.notes}</p>}
                        </div>
                      </div>
                    )}

                    {/* --- EXPORT BUTTONS FOR HISTORY --- */}
                    <div className="flex justify-end gap-2 mb-4">
                      <span className="text-xs text-slate-400 self-center mr-2">Export this plan:</span>
                      <button onClick={() => downloadPlan('pdf', item.plan, `history-plan-${item.id}`, 'Fitness_History')} className="text-xs bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded shadow">PDF</button>
                      <button onClick={() => downloadPlan('word', item.plan, null, 'Fitness_History')} className="text-xs bg-blue-600 hover:bg-blue-700 text-white px-3 py-1 rounded shadow">Word</button>
                    </div>

                    <div id={`history-plan-${item.id}`} className="prose prose-sm max-w-none">
                      <MemoizedMarkdown content={item.plan} />
                    </div>
                  </div>
                </details>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}